id: 02e0f57c-3d07-4ae4-8532-eeece2083b90
title: TOTK Optimizer
subtitle: Toolkit for TOTK.
description: Developed by MaxLastBreath
version: 2.1.0
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.1
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'MaxLastBreath' }